// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdTggJm3vGZuAzM_J31jP0VmGnzU2bmfg',
    appId: '1:575743655056:web:ea897b1fac2f4d2a89ec15',
    messagingSenderId: '575743655056',
    projectId: 'shot-roulette-1308',
    authDomain: 'shot-roulette-1308.firebaseapp.com',
    storageBucket: 'shot-roulette-1308.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsviFX9SJQz29MaB2LUGShSKvE_W2J3RY',
    appId: '1:575743655056:android:68d5c6773eb5ad8c89ec15',
    messagingSenderId: '575743655056',
    projectId: 'shot-roulette-1308',
    storageBucket: 'shot-roulette-1308.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuMyLnNadpfrNmW2eddkeRm3rSg0w6FHg',
    appId: '1:575743655056:ios:8e7a5ff3d52a2d2289ec15',
    messagingSenderId: '575743655056',
    projectId: 'shot-roulette-1308',
    storageBucket: 'shot-roulette-1308.appspot.com',
    iosBundleId: 'com.filipdoganowski.shotRoulette',
  );
}
