// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'cocktail_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$CocktailModelImpl _$$CocktailModelImplFromJson(Map<String, dynamic> json) =>
    _$CocktailModelImpl(
      json['idDrink'] as String?,
      json['strDrink'] as String?,
      json['strDrinkAlternate'] as String?,
      json['strTags'] as String?,
      json['strVideo'] as String?,
      json['strCategory'] as String?,
      json['strIBA'] as String?,
      json['strAlcoholic'] as String?,
      json['strGlass'] as String?,
      json['strInstructions'] as String?,
      json['strInstructionsES'] as String?,
      json['strInstructionsDE'] as String?,
      json['strInstructionsFR'] as String?,
      json['strInstructionsIT'] as String?,
      json['strInstructionsZHHANS'] as String?,
      json['strInstructionsZHHANT'] as String?,
      json['strDrinkThumb'] as String?,
      json['strIngredient1'] as String?,
      json['strIngredient2'] as String?,
      json['strIngredient3'] as String?,
      json['strIngredient4'] as String?,
      json['strIngredient5'] as String?,
      json['strIngredient6'] as String?,
      json['strIngredient7'] as String?,
      json['strIngredient8'] as String?,
      json['strIngredient9'] as String?,
      json['strIngredient10'] as String?,
      json['strIngredient11'] as String?,
      json['strIngredient12'] as String?,
      json['strIngredient13'] as String?,
      json['strIngredient14'] as String?,
      json['strIngredient15'] as String?,
      json['strMeasure1'] as String?,
      json['strMeasure2'] as String?,
      json['strMeasure3'] as String?,
      json['strMeasure4'] as String?,
      json['strMeasure5'] as String?,
      json['strMeasure6'] as String?,
      json['strMeasure7'] as String?,
      json['strMeasure8'] as String?,
      json['strMeasure9'] as String?,
      json['strMeasure10'] as String?,
      json['strMeasure11'] as String?,
      json['strMeasure12'] as String?,
      json['strMeasure13'] as String?,
      json['strMeasure14'] as String?,
      json['strMeasure15'] as String?,
      json['strImageSource'] as String?,
      json['strImageAttribution'] as String?,
      json['strCreativeCommonsConfirmed'] as String?,
      json['dateModified'] as String?,
    );

Map<String, dynamic> _$$CocktailModelImplToJson(_$CocktailModelImpl instance) =>
    <String, dynamic>{
      'idDrink': instance.idDrink,
      'strDrink': instance.strDrink,
      'strDrinkAlternate': instance.strDrinkAlternate,
      'strTags': instance.strTags,
      'strVideo': instance.strVideo,
      'strCategory': instance.strCategory,
      'strIBA': instance.strIBA,
      'strAlcoholic': instance.strAlcoholic,
      'strGlass': instance.strGlass,
      'strInstructions': instance.strInstructions,
      'strInstructionsES': instance.strInstructionsES,
      'strInstructionsDE': instance.strInstructionsDE,
      'strInstructionsFR': instance.strInstructionsFR,
      'strInstructionsIT': instance.strInstructionsIT,
      'strInstructionsZHHANS': instance.strInstructionsZHHANS,
      'strInstructionsZHHANT': instance.strInstructionsZHHANT,
      'strDrinkThumb': instance.strDrinkThumb,
      'strIngredient1': instance.strIngredient1,
      'strIngredient2': instance.strIngredient2,
      'strIngredient3': instance.strIngredient3,
      'strIngredient4': instance.strIngredient4,
      'strIngredient5': instance.strIngredient5,
      'strIngredient6': instance.strIngredient6,
      'strIngredient7': instance.strIngredient7,
      'strIngredient8': instance.strIngredient8,
      'strIngredient9': instance.strIngredient9,
      'strIngredient10': instance.strIngredient10,
      'strIngredient11': instance.strIngredient11,
      'strIngredient12': instance.strIngredient12,
      'strIngredient13': instance.strIngredient13,
      'strIngredient14': instance.strIngredient14,
      'strIngredient15': instance.strIngredient15,
      'strMeasure1': instance.strMeasure1,
      'strMeasure2': instance.strMeasure2,
      'strMeasure3': instance.strMeasure3,
      'strMeasure4': instance.strMeasure4,
      'strMeasure5': instance.strMeasure5,
      'strMeasure6': instance.strMeasure6,
      'strMeasure7': instance.strMeasure7,
      'strMeasure8': instance.strMeasure8,
      'strMeasure9': instance.strMeasure9,
      'strMeasure10': instance.strMeasure10,
      'strMeasure11': instance.strMeasure11,
      'strMeasure12': instance.strMeasure12,
      'strMeasure13': instance.strMeasure13,
      'strMeasure14': instance.strMeasure14,
      'strMeasure15': instance.strMeasure15,
      'strImageSource': instance.strImageSource,
      'strImageAttribution': instance.strImageAttribution,
      'strCreativeCommonsConfirmed': instance.strCreativeCommonsConfirmed,
      'dateModified': instance.dateModified,
    };
